[package]
name = "deconstructing_axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum="0.8.4"
tokio={version="1",features=["macros","rt-multi-thread"]}
serde = { version = "1", features = ["derive"] } # serialization / deserialization
serde_json = "1"     # working with JSON
